
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    environment:
      - APP_ENV=dev
    depends_on:
      - redis

  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
