name: Hello workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Say Hello
        run: echo "Hello from Github Actions!"

      - name: Current date and time
        run: |
          echo "CURRENT_TIME=$(date +'%Y-%M-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Print date
        run: echo ${{ env.CURRENT_TIME }}

      - name: Print name of the Branch
        run: |
          echo "The current brach is ${{ github.ref_name }}"

      - name: List the files
        run: ls -R

      - name: Print the runner's operating system
        run: echo "The operating system is ${{ runner.os }}"

      - name: Simulated Production Compilation
        run: |
          echo "Compiling application layers..."
          echo "❌ CRITICAL ERROR: Database driver connection timed out!"
          exit 1  # This forces the pipeline to instantly crash here

      - name: Emergency Alert Notification Handling
        if: failure()  # This step ONLY runs if a previous step returned a non-zero exit code!
        run: |
          echo "🚨 [ALERT SYSTEM] Production build failed on branch: ${{ github.ref_name }}"
          echo "⚠️ Automated notifications dispatched to the DevOps on-call team."
