name: Log Analyzer CI

on: 
  push:
    branches:
      - master

jobs:
  log-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker container and collect logs
        run: |
          mkdir -p logs
          
          docker run -d --name test-container nginx
          sleep 5
          docker logs test-container > logs/app.log 2>&1

      - name: Cleanup container
        run: docker rm -f test-container

      - name: Make script executable
        run: chmod +x scripting/log_analyzer.sh

      - name: Run log analyzer
        run: ./scripting/log_analyzer.sh logs > result.txt
