name: Log Analyzer CI

on: 
  push:
    branches:
      - master

jobs:
  log-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create sample logs
        run: |
          mkdir -p logs
          echo "info: app started" > logs/app.log
          echo "warning: something minor" >> logs/app.log

      - name: Make script executable
        run: chmod +x scripting/log_analyzer.sh

      - name: Run log analyzer
        run: |
          ERRORS=$(grep -i "error" logs/*.log | wc -l)
          echo "Total errors: $ERRORS"
               
          if [ "$ERRORS" -gt 1 ]; then
             echo "Too many errors! Failing..."
             exit 1
             else
                echo "All good"
                fi
